import React from 'react'
import { Button } from '@/components/button'
import { GradientBackground } from '@/components/gradient'
import { Container } from '@/components/container'

const privacyPolicy = () => {
  return (
    <>
      <GradientBackground />
      <Container className="relative isolate flex h-full flex-col items-center justify-center py-20 text-center sm:py-32">
        <div className="prose text-left">
          <h1>Privacy Policy</h1>
          <p>Last updated: December 03, 2024</p>
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law protects
            You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the
            Service, You agree to the collection and use of information in accordance
            with this Privacy Policy.
          </p>
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined
            under the following conditions. The following definitions shall have the
            same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <p>
                <strong>Account</strong> means a unique account created for You to
                access our Service or parts of our Service.
              </p>
            </li>
            <li>
              <p>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by or is under common control with a party, where
                &quot;control&quot; means ownership of 50% or more of the shares,
                equity interest or other securities entitled to vote for election of
                directors or other managing authority.
              </p>
            </li>
            <li>
              <p>
                <strong>Application</strong> refers to FarmCast, the software program
                provided by the Company.
              </p>
            </li>
            <li>
              <p>
                <strong>Company</strong> (referred to as either &quot;the
                Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
                this Agreement) refers to FarmCast.
              </p>
            </li>
            <li>
              <p><strong>Country</strong> refers to: Indonesia</p>
            </li>
            <li>
              <p>
                <strong>Device</strong> means any device that can access the Service
                such as a computer, a cellphone or a digital tablet.
              </p>
            </li>
            <li>
              <p>
                <strong>Personal Data</strong> is any information that relates to an
                identified or identifiable individual.
              </p>
            </li>
            <li>
              <p><strong>Service</strong> refers to the Application.</p>
            </li>
            <li>
              <p>
                <strong>Service Provider</strong> means any natural or legal person
                who processes the data on behalf of the Company. It refers to
                third-party companies or individuals employed by the Company to
                facilitate the Service, to provide the Service on behalf of the
                Company, to perform services related to the Service or to assist the
                Company in analyzing how the Service is used.
              </p>
            </li>
            <li>
              <p>
                <strong>Usage Data</strong> refers to data collected automatically,
                either generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page visit).
              </p>
            </li>
            <li>
              <p>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of which such
                individual is accessing or using the Service, as applicable.
              </p>
            </li>
          </ul>
          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but is not
            limited to:
          </p>
          <ul>
            <li>Usage Data</li>
          </ul>
          <h4>Usage Data</h4>
          <p> <strong>Definition:</strong> Usage Data refers to information that is collected automatically while using the
            Service. This data helps us improve functionality, identify trends, and enhance user experience. </p>
          <p> Usage Data may include, but is not limited to: </p>
          <ul>
            <li>Your Device&apos;s Internet Protocol (IP) address, which identifies your device on a network.</li>
            <li>Browser type and version to ensure compatibility with our Service.</li>
            <li>The specific pages of our Service that You visit, providing insight into user preferences.</li>
            <li>The time and date of Your visit and the time spent on each page, helping us analyze usage patterns.</li>
            <li>Unique device identifiers, aiding in delivering a customized experience.</li>
            <li>Diagnostic data to identify and fix technical issues promptly.</li>
          </ul>
          <p> When accessing our Service through a mobile device, additional data may be collected automatically, such as: </p>
          <ul>
            <li>The type of mobile device You use, enabling us to optimize the Service for different device types.</li>
            <li>Your mobile device’s unique ID, used for identifying returning users.</li>
            <li>The IP address of your mobile device.</li>
            <li>Your mobile operating system and version.</li>
            <li>The type of mobile internet browser used.</li>
            <li>Diagnostic and performance-related data to ensure a seamless experience.</li>
          </ul>
          <p> Additionally, we may collect information automatically sent by Your browser when You visit our Service or access
            it through a mobile device. </p>
          <h4>Information Collected While Using the Application</h4>
          <p> To provide certain features of Our Application, we may collect specific data with Your prior permission. The types
            of information we may collect include: </p>
          <ul>
            <li> <strong>Location Information:</strong> Details about your geographical location are collected to provide
              location-based features, such as localized content or services. This data may include precise GPS location or
              approximate location based on network data. </li>
            <li> <strong>Camera and Photo Library Access:</strong> Information from your device&apos;s camera or photo library is
              used to enable features such as photo uploads, document scanning, and media sharing. </li>
          </ul>
          <p> This data may be stored either on Your device or securely on Our servers or those of Our trusted Service
            Providers. </p>
          <p> You can enable or disable access to this data at any time through Your Device&apos;s settings. </p>
          <h3>Use of Your Personal Data</h3>
          <p> We process and use Your Personal Data for various purposes to ensure a better experience and comply with legal and
            operational requirements. These include: </p>
          <ul>
            <li> <strong>Providing Seasonal Forecasts:</strong> Using your location data, we provide detailed, localized weather
              forecasts and other environment-related insights relevant to your area. </li>
            <li> <strong>Image Classification and Recommendations:</strong> Data from your photos and interactions are used with
              external providers to provide personalized and accurate information, such as image-based search or
              recommendations. </li>
            <li> <strong>Maintaining and Improving Our Service:</strong> This includes monitoring usage, identifying and fixing
              bugs, and rolling out updates to enhance functionality. </li>
            <li> <strong>Managing Your Account:</strong> To provide registered users with access to exclusive features and
              functionalities based on their account settings and preferences. </li>
            <li> <strong>Fulfilling Contracts:</strong> Using Your data to comply with legal agreements, such as purchase or
              subscription contracts made through Our Service. </li>
            <li> <strong>Communicating with You:</strong> To send updates, announcements, security alerts, and other information
              relevant to Your use of the Service via email, SMS, phone calls, or push notifications. </li>
            <li> <strong>Offering Promotions:</strong> To provide you with news, special offers, and information about goods or
              services similar to those you have already shown interest in, unless You opt out. </li>
            <li> <strong>Responding to Your Requests:</strong> To handle inquiries, support requests, or feedback you provide.
            </li>
            <li> <strong>Business Transfers:</strong> Your data may be part of an asset transfer in the event of a merger,
              acquisition, or similar corporate restructuring. </li>
            <li> <strong>Data Analysis and Research:</strong> To analyze usage trends, evaluate the effectiveness of promotional
              campaigns, and improve our Service, products, marketing, and overall user experience. </li>
          </ul>
          <h3>Sharing Your Personal Information</h3>
          <p> We may share Your information under the following circumstances: </p>
          <ul>
            <li> <strong>With Service Providers:</strong> To facilitate our Service, perform Service-related functions, or
              assist us in analyzing usage trends. </li>
            <li> <strong>For Legal Reasons:</strong> If required to comply with legal obligations, court orders, or to protect
              our rights and assets. </li>
            <li> <strong>Business Transfers:</strong> During negotiations or completion of mergers, acquisitions, or sales of
              assets. </li>
            <li> <strong>With Your Consent:</strong> If explicitly agreed upon, we may share your information for specific
              purposes. </li>
          </ul>

          <ul>
            <li>
              <strong>With Service Providers:</strong> We may share Your personal
              information with Service Providers to monitor and analyze the use of our
              Service, to contact You.
            </li>
            <li>
              <strong>For business transfers:</strong> We may share or transfer Your
              personal information in connection with, or during negotiations of, any
              merger, sale of Company assets, financing, or acquisition of all or a
              portion of Our business to another company.
            </li>
            <li>
              <strong>With Affiliates:</strong> We may share Your information with Our
              affiliates, in which case we will require those affiliates to honor this
              Privacy Policy. Affiliates include Our parent company and any other
              subsidiaries, joint venture partners or other companies that We control
              or that are under common control with Us.
            </li>
            <li>
              <strong>With business partners:</strong> We may share Your information
              with Our business partners to offer You certain products, services or
              promotions.
            </li>
            <li>
              <strong>With other users:</strong> when You share personal information
              or otherwise interact in the public areas with other users, such
              information may be viewed by all users and may be publicly distributed
              outside.
            </li>
            <li>
              <strong>With Your consent</strong>: We may disclose Your personal
              information for any other purpose with Your consent.
            </li>
          </ul>
          <h3>Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will retain
            and use Your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your data to
            comply with applicable laws), resolve disputes, and enforce our legal
            agreements and policies.
          </p>
          <p>
            The Company will also retain Usage Data for internal analysis purposes.
            Usage Data is generally retained for a shorter period of time, except when
            this data is used to strengthen the security or to improve the
            functionality of Our Service, or We are legally obligated to retain this
            data for longer time periods.
          </p>
          <h3>Transfer of Your Personal Data</h3>
          <p>
            Your information, including Personal Data, is processed at the Company&apos;s
            operating offices and in any other places where the parties involved in
            the processing are located. It means that this information may be
            transferred to — and maintained on — computers located outside of Your
            state, province, country or other governmental jurisdiction where the data
            protection laws may differ than those from Your jurisdiction.
          </p>
          <p>
            Your consent to this Privacy Policy followed by Your submission of such
            information represents Your agreement to that transfer.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that Your
            data is treated securely and in accordance with this Privacy Policy and no
            transfer of Your Personal Data will take place to an organization or a
            country unless there are adequate controls in place including the security
            of Your data and other personal information.
          </p>
          <h3>Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the
            Personal Data that We have collected about You.
          </p>
          <p>
            Our Service may give You the ability to delete certain information about
            You from within the Service.
          </p>
          <p>
            You may update, amend, or delete Your information at any time by signing
            in to Your Account, if you have one, and visiting the account settings
            section that allows you to manage Your personal information. You may also
            contact Us to request access to, correct, or delete any personal
            information that You have provided to Us.
          </p>
          <p>
            Please note, however, that We may need to retain certain information when
            we have a legal obligation or lawful basis to do so.
          </p>
          <h3>Disclosure of Your Personal Data</h3>
          <h4>Business Transactions</h4>
          <p>
            If the Company is involved in a merger, acquisition or asset sale, Your
            Personal Data may be transferred. We will provide notice before Your
            Personal Data is transferred and becomes subject to a different Privacy
            Policy.
          </p>
          <h4>Law enforcement</h4>
          <p>
            Under certain circumstances, the Company may be required to disclose Your
            Personal Data if required to do so by law or in response to valid requests
            by public authorities (e.g. a court or a government agency).
          </p>
          <h4>Other legal requirements</h4>
          <p>
            The Company may disclose Your Personal Data in the good faith belief that
            such action is necessary to:
          </p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          <h3>Security of Your Personal Data</h3>
          <p>
            The security of Your Personal Data is important to Us, but remember that
            no method of transmission over the Internet, or method of electronic
            storage is 100% secure. While We strive to use commercially acceptable
            means to protect Your Personal Data, We cannot guarantee its absolute
            security.
          </p>
          <h2>Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone under
            the age of 13. If You are a parent or guardian and You are aware that Your
            child has provided Us with Personal Data, please contact Us. If We become
            aware that We have collected Personal Data from anyone under the age of 13
            without verification of parental consent, We take steps to remove that
            information from Our servers.
          </p>
          <p>
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent&apos;s consent before We collect and use that information.
          </p>
          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by
            Us. If You click on a third party link, You will be directed to that third
            party&apos;s site. We strongly advise You to review the Privacy Policy of every
            site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content,
            privacy policies or practices of any third party sites or services.
          </p>
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of
            any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our Service,
            prior to the change becoming effective and update the &quot;Last
            updated&quot; date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are posted
            on this page.
          </p>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul>
            <li>By email: baghiz.zuhdi@icloud.com</li>
          </ul>
        </div>
        <Button href="/" variant="outline" className="mt-8">
          Go back home
        </Button>
      </Container>
    </>
  )
}

export default privacyPolicy